AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:

  AssignmentSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Docker App

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 167.103.72.80/32

        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  AssignmentEC2:
    Type: AWS::EC2::Instance
    Properties:

      InstanceType: t2.micro

      ImageId: !Ref LatestAmiId

      SecurityGroupIds:
        - !Ref AssignmentSG

      UserData:
        Fn::Base64: |
          #!/bin/bash

          sudo  update -y

          sudo dnf install docker -y

          sudo systemctl start docker
          sudo systemctl enable docker

          docker pull sushms95/flask-assignment:latest

          docker run -d \
          --name flask-app \
          --restart always \
          -p 5000:5000 \
          sushms95/flask-assignment:latest
